# Generated by Django 3.1.1 on 2020-09-10 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qanda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
