# Generated by Django 3.1.1 on 2020-09-11 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qanda', '0003_auto_20200910_2226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='tags',
            new_name='tag',
        ),
    ]
