# Generated by Django 3.1.1 on 2020-09-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qanda', '0005_auto_20200911_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.ManyToManyField(blank=True, related_name='questions', to='qanda.Answer'),
        ),
    ]
