# Generated by Django 3.1.1 on 2020-09-14 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qanda', '0010_auto_20200914_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='qanda.answer'),
        ),
    ]
