# Generated by Django 3.1.1 on 2020-09-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qanda', '0012_auto_20200914_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ManyToManyField(related_name='questions', to='qanda.Question'),
        ),
    ]
