# Generated by Django 3.1.1 on 2020-09-14 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qanda', '0013_answer_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
    ]
