# Generated by Django 3.1.1 on 2020-09-14 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qanda', '0014_remove_question_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='body',
            field=models.TextField(blank=True, default=None),
        ),
    ]
