# Generated by Django 3.1.1 on 2020-09-14 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qanda', '0015_auto_20200914_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ManyToManyField(related_name='answers', to='qanda.Question'),
        ),
    ]
