# Generated by Django 3.1.1 on 2020-09-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qanda', '0017_auto_20200914_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.ManyToManyField(blank=True, related_name='questions', to='qanda.Answer'),
        ),
    ]
